name: "Dev deployment"

concurrency: 1

on:
  push:
    branches:
      - staging
  pull_request:
    types:
      - opened
    branches:
      - staging

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  VENV_PATH: /Users/kevin.potter/Desktop/dbdemos_cdc/actions-runner-venv/bin/activate

jobs:
  validate:
    name: "Validate bundle"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: source $VENV_PATH
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate
        working-directory: declarative-pipeline-cdc
        env:
          DATABRICKS_BUNDLE_ENV: dev

  deploy:
    name: "Deploy bundle"
    runs-on: self-hosted
    needs:
      - validate
    steps:
      - uses: actions/checkout@v5
      - run: source $VENV_PATH
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy
        working-directory: declarative-pipeline-cdc
        env:
          DATABRICKS_BUNDLE_ENV: dev

  run_pipeline:
    name: "Run pipeline update"
    runs-on: self-hosted
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v5
      - run: source $VENV_PATH
      - uses: databricks/setup-cli@main
      - run: databricks bundle run python_cdc_flow --refresh-all
        working-directory: declarative-pipeline-cdc
        env:
          DATABRICKS_BUNDLE_ENV: dev
