name: "Production deployment"

concurrency: 1

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  VENV_PATH: actions-runner-venv/bin/activate

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: source $VENV_PATH
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy
        working-directory: declarative-pipeline-cdc
        env:
          DATABRICKS_BUNDLE_ENV: prod

  run_pipeline:
    name: "Run pipeline update"
    runs-on: self-hosted
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v5
      - run: source $VENV_PATH
      - uses: databricks/setup-cli@main
      - run: databricks bundle run python_cdc_flow --refresh-all
        working-directory: declarative-pipeline-cdc
        env:
          DATABRICKS_BUNDLE_ENV: prod
