name: "Production deployment"

concurrency: 1

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - run: pip install dbx_test
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy
        working-directory: declarative-pipeline-cdc
        env:
          DATABRICKS_BUNDLE_ENV: prod

  run_pipeline:
    name: "Run pipeline update"
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v5
      - uses: databricks/setup-cli@main
      - run: databricks bundle run python_cdc_flow --refresh-all
        working-directory: declarative-pipeline-cdc
        env:
          DATABRICKS_BUNDLE_ENV: prod
